### ISSUE TITLE
Error saving plots after first epoch (x or y dimension incorrect)

### ISSUE THREAD

**Issue by roelofvandijk** [GeorgeSeif/Semantic-Segmentation-Suite#118]
I encountered this error.

Not using  `--validation_step 5`  works. 

Parameters used:

```
python train.py \
--num_epochs 400 \
--crop_height 480 \
--crop_width 480 \
--dataset "dataset" \
--batch_size 1 \
--num_val_images 3 \
--h_flip "True" \
--v_flip "True" \
--rotation 45 \
--brightness 0.2 \
--model "FC-DenseNet56" \
--frontend "ResNet101" \
--validation_step 5
```

Error:

```
Validation precision =  0.32297179946183474
Validation recall =  0.21812934027777778
Validation F1 score =  0.1857004262121048
Validation IoU score =  0.11299733525373462
[2018-10-12 15:34:30] Remaining training time = 2 hours 35 minutes 18 seconds

[2018-10-12 15:34:37] Epoch = 1 Count = 20 Current_Loss = 1.7129 Time = 5.67
[2018-10-12 15:34:42] Epoch = 1 Count = 40 Current_Loss = 1.6329 Time = 5.74
Saving latest checkpoint
[2018-10-12 15:34:48] Remaining training time = 1 hours 52 minutes 7 seconds

Traceback (most recent call last):
  File "train.py", line 308, in <module>
    ax1.plot(range(epoch+1), avg_scores_per_epoch)
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/__init__.py", line 1717, in inner
    return func(ax, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1372, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 404, in _grab_next_args
    for seg in self._plot_args(this, kwargs):
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 384, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 243, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (2,) and (1,)
```

**Comment by x7hkvip** [comment]
Hi,I meet the same problem,how to fix it?Thanks a lot for your help!

**Comment by roelofvandijk** [comment]
Try deleting the --validation_step parameter (reverting to default).
