### ISSUE TITLE
test.py problem 

### ISSUE THREAD

**Issue by yghcats** [GeorgeSeif/Semantic-Segmentation-Suite#119]
Hi，I'm just testing problems：

1. I command line execution.：python test.py --checkpoint_path models/resnet_v2_50.ckpt  --model RefineNet
2. No code added.
3. tensorflow version : 1.4.0
Am I trying to update the tensorflow version or is this error?
error info:
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    saver.restore(sess, args.checkpoint_path)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "Conv_10/biases" not found in checkpoint files models/resnet_v2_50.ckpt
	 [[Node: save_1/RestoreV2_4 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_4/tensor_names, save_1/RestoreV2_4/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_107/_1239 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_121_save_1/RestoreV2_107", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'save_1/RestoreV2_4', defined at:
  File "test.py", line 42, in <module>
    saver=tf.train.Saver(max_to_keep=1000)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1040, in __init__
    self.build()
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "Conv_10/biases" not found in checkpoint files models/resnet_v2_50.ckpt
	 [[Node: save_1/RestoreV2_4 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_4/tensor_names, save_1/RestoreV2_4/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_107/_1239 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_121_save_1/RestoreV2_107", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by GeorgeSeif** [comment]
Well your checkpoint path is incorrect! You are trying to use a classification checkpoint for a segmentation model. You'll need to train first :)
