### ISSUE TITLE
RefineNet Crashes--Gradients and Variables different size??

### ISSUE THREAD

**Issue by CJMenart** [GeorgeSeif/Semantic-Segmentation-Suite#144]
- **What are your command line arguments?:** python train.py --checkpoint_step 2 --dataset XXXX --crop_height 400 --crop_width 400 --num_val_images 2000 --h_flip True --rotation 180 --model RefineNet

- **Have you written any custom code?**: No

- **What have you done to try and solve this issue?:** Nothing yet. I may have a crack at it if there's time in the work day, but this is a bug I've never seen before.

- **TensorFlow version?**: 1.8

### Describe the problem
RefineNet with the above command line arguments fails. It's a simple 2-class problem, I've run the same data through PSPNet without any issue whatever. I'll include the stack trace I got below--it looks like the gradients mismatch the spatial size of their corresponding variable in one of the upsampling blocks? I've not the foggiest how that could come about.

### Source code / logs

***** Begin training *****
Dataset --> XXXX
Model --> RefineNet
Crop Height --> 400
Crop Width --> 400
Num Epochs --> 300
Batch Size --> 1
Num Classes --> 2
Data Augmentation:
	Vertical Flip --> False
	Horizontal Flip --> True
	Brightness Alteration --> None
	Rotation --> 180.0

Traceback (most recent call last):
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,26,26,256] vs. [1,25,25,256]
	 [[Node: gradients/Add_7_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/Add_7_grad/Shape, gradients/Add_7_grad/Shape_1-1-1-VecPermuteNCHWToNHWC-LayoutOptimizer/_1345)]]
	 [[Node: gradients/Add_24_grad/Shape/_1293 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3768_gradients/Add_24_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 200, in <module>
    _,current=sess.run([opt,loss],feed_dict={net_input:input_image_batch,net_output:output_image_batch})
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,26,26,256] vs. [1,25,25,256]
	 [[Node: gradients/Add_7_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/Add_7_grad/Shape, gradients/Add_7_grad/Shape_1-1-1-VecPermuteNCHWToNHWC-LayoutOptimizer/_1345)]]
	 [[Node: gradients/Add_24_grad/Shape/_1293 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3768_gradients/Add_24_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'gradients/Add_7_grad/BroadcastGradientArgs', defined at:
  File "train.py", line 99, in <module>
    opt = tf.train.RMSPropOptimizer(learning_rate=0.0001, decay=0.995).minimize(loss, var_list=[var for var in tf.trainable_variables()])
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 414, in minimize
    grad_loss=grad_loss)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 526, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 494, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 636, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 385, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 636, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py", line 842, in _AddGrad
    rx, ry = gen_array_ops.broadcast_gradient_args(sx, sy)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 674, in broadcast_gradient_args
    "BroadcastGradientArgs", s0=s0, s1=s1, name=name)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'Add_7', defined at:
  File "train.py", line 95, in <module>
    network, init_fn = model_builder.build_model(model_name=args.model, frontend=args.frontend, net_input=net_input, num_classes=num_classes, crop_width=args.crop_width, crop_height=args.crop_height, is_training=True)
  File "/ZZZZ/builders/model_builder.py", line 61, in build_model
    network, init_fn = build_refinenet(net_input, preset_model = model_name, frontend=frontend, num_classes=num_classes, is_training=is_training)
  File "/ZZZZ/models/RefineNet.py", line 176, in build_refinenet
    low[1]=RefineBlock(high[1],low[0]) # High input = ResNet 1/16, Low input = Previous 1/16
  File "/ZZZZ/models/RefineNet.py", line 138, in RefineBlock
    fuse = MultiResolutionFusion(rcu_high, low_inputs,n_filters=256)
  File "/ZZZZ/models/RefineNet.py", line 108, in MultiResolutionFusion
    return tf.add(conv_low_up, conv_high)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 297, in add
    "Add", x=x, y=y, name=name)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/YYYY/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [1,26,26,256] vs. [1,25,25,256]
	 [[Node: gradients/Add_7_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/Add_7_grad/Shape, gradients/Add_7_grad/Shape_1-1-1-VecPermuteNCHWToNHWC-LayoutOptimizer/_1345)]]
	 [[Node: gradients/Add_24_grad/Shape/_1293 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3768_gradients/Add_24_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by CJMenart** [comment]
Update: I pretty much have it figured out, I believe. The gradient bits in the error message were a red herring. This network fails whenever the input images size is not a multiple of 32. The reason is that the downsampling takes the feature size in half five times, but then when we sample back up, we just multiply the feature size by two. So if you go from a size of 25 down to 12, the upsampling will go from 12 to 24--but the size-24 and 25 features are supposed to be added together, and they mismatch.

To correct this, I would recommend saving the actual size of the features as each scale as you go through up/down sampling in RefineNet. Or, b/c it's easier with being able to switch out backbones, you could just compute the correct sizes for each scale from the original image scale. But just upsampling by a factor of 2 will give you this error.
