### ISSUE TITLE
Command line arguments for crop_height and crop_width creates exception

### ISSUE THREAD

**Issue by mainakbiswas** [GeorgeSeif/Semantic-Segmentation-Suite#17]
If I run python main.py with default parameters. everything works fine.

However if I do this 
`python main.py --num_epochs 3 --crop_height 150 --crop_width 150`
or any other value I get an exception. The exception is copied below. The problem occurs here `ConcatOp : Dimensions of inputs should match: shape[0] = [1,8,8,48] vs. shape[1] = [1,9,9,288]`, 

The values in the exception for the shape mismatch is different depending on the input.

for e.g.: `python main.py --num_epochs 3 --crop_height 100 --crop_width 120`
`ConcatOp : Dimensions of inputs should match: shape[0] = [1,6,6,48] vs. shape[1] = [1,6,7,288]`

I was hoping to use it for images of different dimensions than the ones in CamVid dataset.

The exception looks like this
```
Traceback (most recent call last):
  File "main.py", line 278, in <module>
    _,current=sess.run([opt,loss],feed_dict={input:input_image_batch,output:output_image_batch})
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,8,8,48] vs. shape[1] = [1,9,9,288]
	 [[Node: FC-DenseNet56/transitionup6/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FC-DenseNet56/transitionup6/Conv2d_transpose/BiasAdd, FC-DenseNet56/denseblock5/concat_3, gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims/dim)]]
	 [[Node: Mean/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7316_Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'FC-DenseNet56/transitionup6/concat', defined at:
  File "main.py", line 147, in <module>
    network = build_fc_densenet(input, preset_model = args.model, num_classes=num_classes)
  File "models/FC_DenseNet_Tiramisu.py", line 150, in build_fc_densenet
    stack = TransitionUp(block_to_upsample, skip_connection_list[i], n_filters_keep, scope='transitionup%d' % (n_pool + i + 1))
  File "models/FC_DenseNet_Tiramisu.py", line 63, in TransitionUp
    l = tf.concat([l, skip_connection], axis=-1)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1130, in concat
    return gen_array_ops._concat_v2(values=values, axis=axis, name=name)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 700, in _concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [1,8,8,48] vs. shape[1] = [1,9,9,288]
	 [[Node: FC-DenseNet56/transitionup6/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FC-DenseNet56/transitionup6/Conv2d_transpose/BiasAdd, FC-DenseNet56/denseblock5/concat_3, gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims/dim)]]
	 [[Node: Mean/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7316_Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]] 
```

**Comment by GeorgeSeif** [comment]
Okay so, the reason for your error with that crop size is because many segmentation networks will have some downsampling. Now lets say for example a network has 4 pooling layers; this means eventually the input will have it's size divided by 2, 4 times. If the input is of size 150x150, we would end up doing 150/2/2/2/2 (divide by 2 4 times), which gets us 9.375. Unfortunately, TensorFlow would actually round this to 9. Then, when we upsample 4 times we get 9x2x2x2x2 = 144 which is different from your final label size! It'll actually mess things up even earlier during upsampling, as what happened in your case.

That's why you can set the crop size as an input argument! If you want to handle images of different size with the FC-DenseNet which has 5 pooling layers, you will need an image size that is divisible by 2^5 = 32.

If the network had no downsampling whatsoever, then you can just go ahead and set the crop size to the original image size.

**Comment by mainakbiswas** [comment]
Thanks a lot. That really helped me understand what is going on. You rock.
