### ISSUE TITLE
when I ran train.py.I have the problem:subprocess.CalledProcessError: Command '['python', 'utils/get_pretrained_checkpoints.py', '--model=ResNet101']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by sweetboxwwy** [GeorgeSeif/Semantic-Segmentation-Suite#205]
Traceback (most recent call last):
  File "utils/get_pretrained_checkpoints.py", line 19, in <module>
    subprocess.check_output(['wget','http://download.tensorflow.org/models/resnet_v2_101_2017_04_14.tar.gz', "-P", "models"])
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "train.py", line 95, in <module>
    network, init_fn = model_builder.build_model(model_name=args.model, frontend=args.frontend, net_input=net_input, num_classes=num_classes, crop_width=args.crop_width, crop_height=args.crop_height, is_training=True)
  File "D:\Downloads\Semantic-Segmentation-Suite-master\Semantic-Segmentation-Suite-master\builders\model_builder.py", line 47, in build_model
    download_checkpoints("ResNet101")
  File "D:\Downloads\Semantic-Segmentation-Suite-master\Semantic-Segmentation-Suite-master\builders\model_builder.py", line 28, in download_checkpoints
    subprocess.check_output(["python", "utils/get_pretrained_checkpoints.py", "--model=" + model_name])
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python', 'utils/get_pretrained_checkpoints.py', '--model=ResNet101']' returned non-zero exit status 1.

**Comment by YyChen818** [comment]
I also have this problem, would you please tell me that have you solved it?

**Comment by jsolves** [comment]
ResNet download url changed. It was updated in one of the latest commits...

**Comment by YyChen818** [comment]
If so, where can I get the lastest url.

**Comment by YyChen818** [comment]
It might be not. I try to copy the url to download the model, it works. So I don't think it's a problem about url.

**Comment by sweetboxwwy** [comment]
> I also have this problem, would you please tell me that have you solved

**Comment by sweetboxwwy** [comment]
> I also have this problem, would you please tell me that have you solved it?

i have not solve it yet

**Comment by tgiles4** [comment]
I solved this problem for myself.

First, you need to install wget. I found a download here: http://gnuwin32.sourceforge.net/packages/wget.htm

Once you have wget, add it to your path variables and everything should work.

**Comment by sweetboxwwy** [comment]
> I solved this problem for myself.
> 
> First, you need to install wget. I found a download here: http://gnuwin32.sourceforge.net/packages/wget.htm
> 
> Once you have wget, add it to your path variables and everything should work.

i can not open this url...

**Comment by tgiles4** [comment]
Try searching for "wget for windows"

**Comment by YyChen818** [comment]
Thank you so much !!!

**Comment by c-reng** [comment]
> I solved this problem for myself.
> 
> First, you need to install wget. I found a download here: http://gnuwin32.sourceforge.net/packages/wget.htm
> 
> Once you have wget, add it to your path variables and everything should work.

What do you mean by add it to your path variables?

**Comment by sweetboxwwy** [comment]
> Try searching for "wget for windows"

Thank you so much,I solved this problem,but I have the next problem:
Traceback (most recent call last):
  File "D:/Downloads/Semantic-Segmentation-Suite-master/Semantic-Segmentation-Suite-master/train.py", line 175, in <module>
    input_image = utils.load_image(train_input_names[id])
  File "D:\Downloads\Semantic-Segmentation-Suite-master\Semantic-Segmentation-Suite-master\utils\utils.py", line 45, in load_image
    image = cv2.cvtColor(cv2.imread(path,-1), cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by tgiles4** [comment]
When I get this issue, it means opencv didn't read the image

**Comment by YyChen818** [comment]
I got the second problem too, have you solved it?

**Comment by sweetboxwwy** [comment]
> I got the second problem too, have you solved it?

I use spyder to run it correctly,and I used pycharm before

**Comment by YyChen818** [comment]
It may be impolite, can I have your QQ or wechat to communicate?

**Comment by sweetboxwwy** [comment]
> It may be impolite, can I have your QQ or wechat to communicate?

My QQ 1454811452

**Comment by VincentdogLee** [comment]
You can download the pretrained model by yourself and add it to "/models",it works

**Comment by nnk2193** [comment]
> > I got the second problem too, have you solved it?
> 
> I use spyder to run it correctly,and I used pycharm before

can you help me with how to do that?

**Comment by yucheng-china** [comment]
> > I solved this problem for myself.
> > First, you need to install wget. I found a download here: http://gnuwin32.sourceforge.net/packages/wget.htm
> > Once you have wget, add it to your path variables and everything should work.
> 
> What do you mean by add it to your path variables?

Hi, have you finished it now? i have the same question as you, what is by the means of "add it to your path variable?"

**Comment by yucheng-china** [comment]
> I also have this problem, would you please tell me that have you solved it?

have you sloved it ?

**Comment by nnk2193** [comment]
I couldn't solve it. Which dataset you are using?

**Comment by yucheng-china** [comment]
Hi, i use CamVid, i have made it work now, but i don't know how the compare
my resluts to others, which paper we can use for comparison

nnk2193 <notifications@github.com> 于2020年7月10日周五 下午8:58写道：

**Comment by tgiles4** [comment]
> > > I solved this problem for myself.
> > > First, you need to install wget. I found a download here: http://gnuwin32.sourceforge.net/packages/wget.htm
> > > Once you have wget, add it to your path variables and everything should work.
> > 
> > 
> > What do you mean by add it to your path variables?
> 
> Hi, have you finished it now? i have the same question as you, what is by the means of "add it to your path variable?"

If you are on windows, you need to download wget for windows and add it to the OS path variables in your system (Search "add to path variable on Windows")

if you are on linux, you need wget and make sure it's in your path in your bashrc configuration/etc

**Comment by nnk2193** [comment]
There are many standard papers. you may find this paper useful.
Regards,

-- 
*Nikhil Ninad Kulkarni*
MTech(PRSD), IIRS,
ISRO, Department of Space, India.

**Comment by yucheng-china** [comment]
I make it works now, thank your guys very much

2020年7月22日 22:26，"tgiles4" <notifications@github.com>写道：
