### ISSUE TITLE
Training FC-DenseNet103 with my data

### ISSUE THREAD

**Issue by fotsing365** [GeorgeSeif/Semantic-Segmentation-Suite#35]
Hi every one. I have labeled some jpg images using paint and i would like to train the FC-DenseNet103 model with but i get the following error.

Traceback (most recent call last):
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: All dimensions except 3 must match. Input 1 has shape [1 13 13 656] and doesn't match input 0 with shape [1 12 12 240].
	 [[Node: gradients/FC-DenseNet103/transitionup6/concat_grad/ConcatOffset = ConcatOffset[N=2, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/FC-DenseNet103/denseblock1/concat_grad/mod, gradients/FC-DenseNet103/transitionup6/concat_grad/ShapeN, gradients/FC-DenseNet103/transitionup6/concat_grad/ShapeN:1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 276, in <module>
    _,current=sess.run([opt,loss],feed_dict={input:input_image_batch,output:output_image_batch})
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: All dimensions except 3 must match. Input 1 has shape [1 13 13 656] and doesn't match input 0 with shape [1 12 12 240].
	 [[Node: gradients/FC-DenseNet103/transitionup6/concat_grad/ConcatOffset = ConcatOffset[N=2, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/FC-DenseNet103/denseblock1/concat_grad/mod, gradients/FC-DenseNet103/transitionup6/concat_grad/ShapeN, gradients/FC-DenseNet103/transitionup6/concat_grad/ShapeN:1)]]

Caused by op 'gradients/FC-DenseNet103/transitionup6/concat_grad/ConcatOffset', defined at:
  File "main.py", line 169, in <module>
    opt = tf.train.AdamOptimizer(0.0001).minimize(loss, var_list=[var for var in tf.trainable_variables()])
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 359, in minimize
    grad_loss=grad_loss)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 460, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 611, in gradients
    lambda: grad_fn(op, *out_grads))
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 377, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 611, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_grad.py", line 212, in _ConcatGradV2
    op, grad, start_value_index=0, end_value_index=-1, dim_index=-1)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_grad.py", line 137, in _ConcatGradHelper
    offset = gen_array_ops._concat_offset(non_neg_concat_dim, sizes)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 586, in _concat_offset
    "ConcatOffset", concat_dim=concat_dim, shape=shape, name=name)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'FC-DenseNet103/transitionup6/concat', defined at:
  File "main.py", line 139, in <module>
    network = build_fc_densenet(input, preset_model = args.model, num_classes=num_classes)
  File "models/FC_DenseNet_Tiramisu.py", line 150, in build_fc_densenet
    stack = TransitionUp(block_to_upsample, skip_connection_list[i], n_filters_keep, scope='transitionup%d' % (n_pool + i + 1))
  File "models/FC_DenseNet_Tiramisu.py", line 63, in TransitionUp
    l = tf.concat([l, skip_connection], axis=-1)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1175, in concat
    return gen_array_ops._concat_v2(values=values, axis=axis, name=name)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 625, in _concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/home/cedriq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): All dimensions except 3 must match. Input 1 has shape [1 13 13 656] and doesn't match input 0 with shape [1 12 12 240].
	 [[Node: gradients/FC-DenseNet103/transitionup6/concat_grad/ConcatOffset = ConcatOffset[N=2, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/FC-DenseNet103/denseblock1/concat_grad/mod, gradients/FC-DenseNet103/transitionup6/concat_grad/ShapeN, gradients/FC-DenseNet103/transitionup6/concat_grad/ShapeN:1)]]

as attached file an example of my labeled images

![img_48_sleep_space_good](https://user-images.githubusercontent.com/24406778/38558110-0f5911f2-3cc7-11e8-80ea-efe52ce2da12.jpg)
![img_48_sleep_space_good_l](https://user-images.githubusercontent.com/24406778/38558162-2ee7af2e-3cc7-11e8-8e39-5f95d619114e.jpg)

**Comment by GeorgeSeif** [comment]
`InvalidArgumentError (see above for traceback): All dimensions except 3 must match. Input 1 has shape [1 13 13 656] and doesn't match input 0 with shape [1 12 12 240].`

Looks like an error with your image size and the rounding in TensorFlow / Python. Check out this issue:

https://github.com/GeorgeSeif/Semantic-Segmentation-Suite/issues/27

Your images' size must be compatible with the downsampling for your network.

**Comment by fotsing365** [comment]
Hi GeorgeSeif. I have modified the size of my image to 320X288 so that it can respect the indications in (https://github.com/GeorgeSeif/Semantic-Segmentation-Suite/issues/27)  but I get the same error. I don't know if it is because the images are in the format "jpg" instead of "png" as in CamVid
