### ISSUE TITLE
TypeError: Expected binary or unicode string, got <built-in function input>

### ISSUE THREAD

**Issue by alansalinas** [GeorgeSeif/Semantic-Segmentation-Suite#53]
Hi, I'm trying to run main.py in an environment with the installed requirements, but I think there is need for the versions. I believe this is caused by me using a different Tensorflow version.

tensorflow==1.7.0
tensorflow-gpu==1.2.1

`Traceback (most recent call last):
  File "/home/alansalinas/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 518, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/home/alansalinas/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 518, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/home/alansalinas/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 68, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got <built-in function input>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 152, in <module>
    network = build_fc_densenet(input, preset_model = args.model, num_classes=num_classes)
  File "models/FC_DenseNet_Tiramisu.py", line 112, in build_fc_densenet
    stack = slim.conv2d(inputs, n_filters_first_conv, [3, 3], scope='first_conv', activation_fn=None)
  File "/home/alansalinas/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/alansalinas/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1015, in convolution
    inputs = ops.convert_to_tensor(inputs)
  File "/home/alansalinas/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 950, in convert_to_tensor
    as_ref=False)
  File "/home/alansalinas/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1040, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/alansalinas/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/alansalinas/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/alansalinas/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 522, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'builtin_function_or_method'> to Tensor. Contents: <built-in function input>. Consider casting elements to a supported type.`

**Comment by GeorgeSeif** [comment]
Hhmmm I'm not so sure. 

I have:
tensorflow==1.7.0
tensorflow-gpu==1.4.1

And those work fine. But I do see that you're using Python 3. Perhaps that could be the source of the issue? I only tested it with Python 2! 

Let me know :smile:

**Comment by JWFrank** [comment]
I have:
tensorflow-gpu ==1.4.1 or tensorflow-gpu == 1.7
also get this problem

Traceback (most recent call last):
  File "main.py", line 152, in <module>
    network = build_fc_densenet(input, preset_model = args.model, num_classes=num_classes)
  File "models/FC_DenseNet_Tiramisu.py", line 112, in build_fc_densenet
    stack = slim.conv2d(inputs, n_filters_first_conv, [3, 3], scope='first_conv', activation_fn=None)
  File "/home/vll/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/vll/.local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1000, in convolution
    inputs = ops.convert_to_tensor(inputs)
  File "/home/vll/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 836, in convert_to_tensor
    as_ref=False)
  File "/home/vll/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 926, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/vll/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/vll/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/vll/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 472, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <type 'builtin_function_or_method'> to Tensor. Contents: <built-in function input>. Consider casting elements to a supported type.

**Comment by GeorgeSeif** [comment]
Ah okay, mistake on my part!

In one of the recent commits (ICNet) I moved a block of code up in the `main.py` which is causing the screw up. I'm actually adding a quick feature right now and will push a commit that fixes that issue and adds the feature later today. It should work then!

**Comment by GeorgeSeif** [comment]
Just pushed! Can you try it out now?

**Comment by GeorgeSeif** [comment]
Awesome!

**Comment by alansalinas** [comment]
I pulled the latest commits and it worked for me too, I used a new Python 2 environment:

tensorflow-gpu            1.7.0
tensorflow==1.7.0

**Comment by GeorgeSeif** [comment]
Thanks for letting me know Alan, cheers!
