### ISSUE TITLE
Training error, Tensor conversion

### ISSUE THREAD

**Issue by ablacklama** [GeorgeSeif/Semantic-Segmentation-Suite#61]
tf-1.8
python-3.6
I'm training on a custom vehicle dataset and I keep getting this error. 

`
(tf18) C:\Users\ablac\Desktop\Semantic-Segmentation-Suite-master>python main.py --num_epochs=100 --class_balancing="True" --dataset="data" --batch_size=5 --h_flip="True" --model="DeepLabV3_plus-Res50"
C:\Users\ablac\Miniconda3\envs\tf18\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
  from ._conv import register_converters as _register_converters
2018-05-18 15:38:08.603677: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-05-18 15:38:08.741368: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1356] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 9.10GiB
2018-05-18 15:38:08.741429: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1435] Adding visible gpu devices: 0
2018-05-18 15:38:09.105581: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-18 15:38:09.105622: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:929]      0
2018-05-18 15:38:09.106062: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:942] 0:   N
2018-05-18 15:38:09.106257: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8805 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Preparing the model ...
WARNING:tensorflow:From models\DeepLabV3_plus.py:41: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "C:\Users\ablac\Miniconda3\envs\tf18\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Users\ablac\Miniconda3\envs\tf18\lib\site-packages\tensorflow\python\framework\ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\ablac\Miniconda3\envs\tf18\lib\site-packages\tensorflow\python\framework\ops.py", line 947, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float64: 'Tensor("truediv:0", shape=(2,), dtype=float64)'
`
During handling of the above exception, another exception occurred:
`
Traceback (most recent call last):
  File "main.py", line 180, in <module>
    network, init_fn = build_deeplabv3_plus(net_input, preset_model = args.model, num_classes=num_classes)
  File "models\DeepLabV3_plus.py", line 103, in build_deeplabv3_plus
    decoder_features = Upsampling(net, label_size / 4)
  File "models\DeepLabV3_plus.py", line 10, in Upsampling
    return tf.image.resize_bilinear(inputs, size=feature_map_shape)
  File "C:\Users\ablac\Miniconda3\envs\tf18\lib\site-packages\tensorflow\python\ops\gen_image_ops.py", line 2656, in resize_bilinear
    align_corners=align_corners, name=name)
  File "C:\Users\ablac\Miniconda3\envs\tf18\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 533, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'size' of 'ResizeBilinear' Op has type float64 that does not match expected type of int32.
`

here's my class_dict.csv file:
name,r,g,b
None,0,0,0
Building,1,0,0
Fence,2,0,0
Other,3,0,0
Pedestrians,4,0,0
Poles,5,0,0
Roads,7,0,0
Sidewalks,8,0,0
Vegetation,9,0,0
Vehicles,10,0,0
Walls,11,0,0
TrafficSigns,12,0,0

**Comment by ablacklama** [comment]
"DeepLabV3-Res50" doesn't seem to have this error

**Comment by ablacklama** [comment]
huh, somehow now all the different types of models will start training and reducing the loss, until about 5 minutes in the loss will start to increase. My label images use the red color channel as a label (as shown above). And i only have 12 classes. My images are also being cropped but i don't feel like any of this should make the network unable to train

**Comment by GeorgeSeif** [comment]
Hhmm well it seems like that error with `resize_bilinear` is saying that you're passing a `float` as the image size. How about try printing a few things to debug

**Comment by ablacklama** [comment]
The problem is here.

"deeplabv3_plus.py" line 103:decoder_features = Upsampling(net, label_size / 4)

If the size of your labels isn't divisible by 4 then you will get a float and that float will be passed to:

tf.image.resize_bilinear(inputs, size=feature_map_shape)

And since resize rightly only accepts integers for it's size function, you have a problem. 

I don't know how to fix this though because i'm not familiar enough with the model to know if simply casting the float to an integer will mess something up. Got any advice?

**Comment by GeorgeSeif** [comment]
Aahhhh good catch! 

It's actually essentially the same error and corresponding fix as issue #17 

Unfortunately, that's just how some models (Including DeepLabV3 and V3+) work. Because of the downsampling, **you need to have the images cropped to an appropriate size (i.e divisible by 4 in this case)!**

Since many people have run into this problem I think I will add an assertion check to throw an error if images aren't properly cropped, to avoid any confusions.

Cheers!

**Comment by ablacklama** [comment]
to fix this do i need to add another class?
