### ISSUE TITLE
 Incompatible shapes: [2,46,80,256] vs. [2,45,80,256]

### ISSUE THREAD

**Issue by 1453042287** [GeorgeSeif/Semantic-Segmentation-Suite#94]
hi there, when i use the dataset bdd100k to train this (model="RefineNet" and frontend="MobileNetV2") model , erro imported like this:

Traceback (most recent call last):
  File "train-gg.py", line 193, in <module>
    _,current=sess.run([opt,loss],feed_dict={net_input:input_image_batch,net_output:output_image_batch})
  File "/home2/zhen_yang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home2/zhen_yang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home2/zhen_yang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home2/zhen_yang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [2,46,80,256] vs. [2,45,80,256]

i think it's because the padding strategy is incompatible with the conv-layer setting , but i don't konw how to change it, can you give me some suggestions?

**Comment by vid12** [comment]
Hi,
Hi,

Not sure if this will help, but did you you try to set --crop_height and --crop_width to a numbers dividable by 64?

Regards,
Vid

**Comment by GeorgeSeif** [comment]
Thanks for the answer @vid12 ! 

vid12 is right! Please read the FAQs next time :)

**Comment by 1453042287** [comment]
@vid12 thanks a lot！
